### ISSUE TITLE
Question about implementation Decompose

### ISSUE THREAD

**Issue by arstagaev** [kamathis4/NotesAppKMM#3]
Hi:) How Decompose lib implemented in the project? I have seen this in gradle file:
```
api(libs.decompose)
implementation(libs.decompose.compose.multiplatform)
```
But in standard project of KMM i cant implement like that (tried launch from android studio plugin and from KMM Wizard https://terrakok.github.io/Compose-Multiplatform-Wizard/), what need addition for implement Decompose lib like in current project NoteApp?

**Comment by arstagaev** [comment]
In standard sample project of KMM, i cant implement lib, like in this project.

<img width="759" alt="image" src="https://github.com/kamathis4/NotesAppKMM/assets/53790451/be567d53-c9ae-4430-80e0-e0c5cb23aced">

**Comment by adi-kmt** [comment]
Hey @arstagaev, thanks for dropping by.

So there is this file with the extension of .toml, which holds all the dependencies. It is present in the gradle directory.

Once you add the dependencies there, you can access it using libs.<dependencies_name> 

This is called version catalogue and is considered the current 'best practice' over using the build src module.

**Comment by arstagaev** [comment]
Ok, thank you for answer @kamathis4 👍
